=== BarannikovIS/NC1/project1AbstractClassAndInterface/Figures.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="" xmlns="" elementFormDefault="qualified">
<xs:element name="ListFigures">
<xs:complexType>
<xs:sequence>
<xs:element name="figure" minOccurs="1" maxOccurs="3">
<xs:complexType>
<xs:attribute name="name" type="xs:string" use="required" />
<xs:sequence>
<xs:element name="X" minOccurs="1" maxOccurs="1">
<xs:complexType>
<xs:simpleContent>
<xs:extension base="xs:string" />
</xs:simpleContent>
</xs:complexType>
</xs:element>
<xs:element name="Y" minOccurs="1" maxOccurs="1">
<xs:complexType>
<xs:simpleContent>
<xs:extension base="xs:string" />
</xs:simpleContent>
</xs:complexType>
</xs:element>
<xs:element name="Area" minOccurs="1" maxOccurs="1">
<xs:complexType>
<xs:simpleContent>
<xs:extension base="xs:string" />
</xs:simpleContent>
</xs:complexType>
</xs:element>
<xs:element name="Perimetr" minOccurs="1" maxOccurs="1">
<xs:complexType>
<xs:simpleContent>
<xs:extension base="xs:string" />
</xs:simpleContent>
</xs:complexType>
</xs:element>
<xs:element name="Radius" minOccurs="0" maxOccurs="1">
<xs:complexType>
<xs:simpleContent>
<xs:extension base="xs:string" />
</xs:simpleContent>
</xs:complexType>
</xs:element>
<xs:element name="Width" minOccurs="0" maxOccurs="1">
<xs:complexType>
<xs:simpleContent>
<xs:extension base="xs:string" />
</xs:simpleContent>
</xs:complexType>
</xs:element>
<xs:element name="Height" minOccurs="0" maxOccurs="1">
<xs:complexType>
<xs:simpleContent>
<xs:extension base="xs:string" />
</xs:simpleContent>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== BarannikovIS/NC1/project1AbstractClassAndInterface/ListFigures.xml
<?xml version="1.0" encoding="UTF-8"?>
<ListFigures xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Figures.xsd">
  <figure name="Circle">
    <X>10</X>
    <Y>10</Y>
    <Area>2827</Area>
    <Perimetr>188</Perimetr>
    <Radius>30</Radius>
  </figure>
  <figure name="Rectangle">
    <X>5</X>
    <Y>5</Y>
    <Area>300</Area>
    <Perimetr>70</Perimetr>
    <Width>15</Width>
    <Height>20</Height>
  </figure>
  <figure name="Rectangle">
    <X>10</X>
    <Y>10</Y>
    <Area>25</Area>
    <Perimetr>20</Perimetr>
    <Width>5</Width>
    <Height>5</Height>
  </figure>
</ListFigures>
